# -*- coding: utf-8 -*-
"""Task 2:  Data Classification  Using AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nl_MwmFO5ObU0gwT0KrVN_qzlpd780Zp
"""

import pandas as pd
from sklearn.datasets import load_iris

# Load the dataset
iris = load_iris()

# Convert to a DataFrame for easier visualization
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['target'] = iris.target

# Display the first 5 rows
print("Dataset Sample:")
print(df.head())

# Understand the structure
print("\nDataset Shape:", df.shape)
print("Target Species:", iris.target_names)

from sklearn.model_selection import train_test_split

# Separate features (X) and target labels (y)
X = df.drop(columns=['target'])
y = df['target']

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training set size: {X_train.shape[0]} samples")
print(f"Testing set size: {X_test.shape[0]} samples")

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Initialize the model
# max_iter is increased to ensure the optimization algorithm converges
model = LogisticRegression(max_iter=200)

# Train the model using the training data
model.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%")

# Detailed performance report
print("#92;nClassification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))